### ISSUE TITLE
HW1_2_1: sampling from the distribution

### ISSUE THREAD

**Issue by arielbenitah** [ikrets/CS294-158-homeworks#2]
Hi,

First of all, thanks a lot for sharing your solutions of this course. I'm learning a lot from those...
I just have a question: in homework 1_2_1, I don't really understand how you're sampling from the given 'distribution' (image of Alan Turing). You're using a **uniform** distribution (`np.random.choice`), as far as I understand, in order to sample from a given distribution there is a method called [inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling). In the lectures they are discussing this method. 
Can you explain what is the rational of using a uniform distribution and not this inverse transform sampling.

Thnaks a lot

**Comment by ikrets** [comment]
Hey,

you are talking about this cell, right?
```python
samples = np.random.choice(200 * 200, p=true_probs.reshape(-1), size=100000)
samples_x = samples % 200
samples_y = samples // 200
samples = np.stack([samples_x, samples_y], axis=1)
train, val = train_test_split(samples, test_size=0.2)
```
The `p` parameter of `np.random.choice` assigns a probability to every possible choice. So we have a choice of 200 * 200 pixels with corresponding probabilities. I don't think inverse transform sampling is needed here, as the probability distribution is given to you directly (for every possible x1, x2 you know p(x1, x2) from the turing picture). Does that make sense?

**Comment by arielbenitah** [comment]
Hi,
thanks for the answer. My only concern is that you're using a **uniform** distribution to sample from the Turing image - which is not uniformly distributed... My question is how to sample from this given distribution (Turing image)? Maybe your way of sampling from it is the right way: I just don't succeed to figure it...
Obviously, I am missing something :-)

**Comment by ikrets** [comment]
Say you have a distribution x in {0, 1, 2} with p(0) = 0.1, p(1) = 0.1, p(2) = 0.8.
You can sample from this distribution using `np.random.choice([0, 1, 2], p=[0.1, 0.1, 0.8])`. So you are using `np.random.choice` but you are not sampling from the uniform distribution.

**Comment by arielbenitah** [comment]
Hi, thanks a lot for the answer! It took me time :-) but finally from your last answer, I understand what you mean. Thanks a lot :-)
